# Generated by Django 2.2.6 on 2019-10-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pk',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
