# Generated by Django 3.0.2 on 2020-01-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('idtable1', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'table1',
                'managed': False,
            },
        ),
    ]
