# Generated by Django 2.2.5 on 2019-09-25 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aritlce',
            new_name='Article',
        ),
    ]
