# Generated by Django 2.2.5 on 2019-10-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191024_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
